[platformio]
default_envs = esp32-c6-dev

[env]
platform = espressif32
framework = espidf
monitor_speed = 115200

build_flags =
    -std=gnu++20
    -Wall
    -Wextra

monitor_filters =
    esp32_exception_decoder
    time

[env:esp32-c6-dev]
board = seeed_xiao_esp32c6

build_flags =
    ${env.build_flags}
    -DCONFIG_MOTOR_USE_MOCK=1

[env:esp32-c6-hardware]
board = seeed_xiao_esp32c6

build_flags =
    ${env.build_flags}
    -DCONFIG_MOTOR_USE_MOCK=0